# Generated by Django 3.1.1 on 2020-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCommission',
            fields=[
                ('commission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=32768)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_type_id', models.IntegerField()),
                ('title', models.TextField(max_length=32768)),
                ('created', models.DateTimeField()),
                ('user', models.TextField(max_length=1024)),
                ('workingGroupId', models.IntegerField()),
                ('commissionId', models.IntegerField()),
                ('deletable', models.BooleanField()),
                ('sensitive', models.BooleanField()),
                ('status', models.TextField(max_length=32)),
                ('productionOffice', models.TextField(max_length=8)),
            ],
        ),
    ]
