# Generated by Django 3.1.1 on 2020-09-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedcommission',
            old_name='commission_id',
            new_name='id',
        ),
    ]
