# Generated by Django 3.1.1 on 2020-09-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0002_auto_20200914_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_type_id',
            new_name='projectTypeId',
        ),
    ]
