# Generated by Django 3.1.1 on 2020-09-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0003_auto_20200914_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedProject',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbitmq.cachedcommission')),
            ],
        ),
    ]
