# Generated by Django 3.1.1 on 2020-09-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KinesisTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(db_index=True, max_length=255)),
                ('shard_id', models.CharField(max_length=255)),
                ('sequence_number', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('processing_host', models.CharField(max_length=255, null=True)),
                ('millis_behind_latest', models.BigIntegerField()),
                ('last_exception', models.CharField(max_length=2048, null=True)),
                ('exception_trace', models.CharField(max_length=32768, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
