# Generated by Django 3.1.1 on 2020-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=64)),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('atom_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('STARTED', 'Started'), ('FINISHED', 'Success'), ('FINISHED_WARNING', 'Non-fatal error'), ('FAILED_TOTAL', 'Failed'), ('WAITING', 'Waiting'), ('ABORT_PENDING', 'Abort requested'), ('ABORTED', 'Cancelled by admin')], max_length=64)),
                ('atom_title', models.CharField(default='Unknown title', max_length=1024)),
                ('user_email', models.CharField(db_index=True, default='Unknown user', max_length=1024)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('s3_path', models.CharField(max_length=2048, null=True)),
                ('retry_number', models.IntegerField(default=0)),
                ('processing', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PacFormXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('received', models.DateTimeField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('pacdata_url', models.CharField(max_length=4096)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('DOWNLOADING', 'Downloading'), ('INPROGRESS', 'In progress'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], db_index=True, default='UNPROCESSED', max_length=32)),
                ('celery_task_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
    ]
